apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: pipeline-kata-only
spec:
  params:
  tasks:
    - name: build-small
      taskRef:
        name: build-small
    - name: build-medium
      taskRef:
        name: build-medium
    - name: build-large
      taskRef:
        name: build-large
---
apiVersion: tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: listener-kata-only
spec:
  resourcetemplates:
    - apiVersion: tekton.dev/v1
      kind: PipelineRun
      metadata:
        name: run
      spec:
        podTemplate:
          runtimeClassName: medium
        securityContext:
          privileged: true
        pipelineRef:
            name: pipeline-kata-only
---
apiVersion: tekton.dev/v1
kind: TriggerBinding
metadata:
  name: listener-kata-only
spec:
  params:
---
apiVersion: tekton.dev/v1
kind: EventListener
metadata:
  name: listener-kata-only
spec:
  triggers:
    - binding:
        name: listener-kata-only
      template:
        name: listener-kata-only
