apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: build-small
  labels:
    runtimeClassName: small
spec:
  params:
  steps:
    - name: build
      image: icr.io/continuous-delivery/base-images/base:v1.6.0
      script: |
        #!/bin/bash
        echo "Build small!"
        sleep 2m
        echo "Wake!"
        head /proc/cpuinfo
        head /proc/meminfo
        lsblk
        df -h .
---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: build-medium
  labels:
    runtimeClassName: medium
spec:
  params:
  steps:
    - name: build
      image: icr.io/continuous-delivery/base-images/base:v1.6.0
      script: |
        #!/bin/bash
        echo "Build medium!"
        sleep 9m
        echo "Wake!"
        head /proc/cpuinfo
        head /proc/meminfo
        lsblk
        df -h .
---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: build-large
  labels:
    runtimeClassName: large
spec:
  params:
  steps:
    - name: build
      image: icr.io/continuous-delivery/base-images/base:v1.6.0
      script: |
        #!/bin/bash
        echo "Build large!"
        sleep 6m
        echo "Wake!"
        head /proc/cpuinfo
        head /proc/meminfo
        lsblk
        df -h .
---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: build-x86-large
  labels:
    runtimeClassName: x86-large
spec:
  params:
  steps:
    - name: build
      image: icr.io/continuous-delivery/base-images/base:v1.6.0
      script: |
        #!/bin/bash
        echo "Build x86-large!"
        sleep 15m
        echo "Wake!"
        head /proc/cpuinfo
        head /proc/meminfo
        lsblk
        df -h .
---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: build-x86-xlarge
  labels:
    runtimeClassName: x86-xlarge
spec:
  params:
  steps:
    - name: build
      image: icr.io/continuous-delivery/base-images/base:v1.6.0
      script: |
        #!/bin/bash
        echo "Build x86-xlarge!"
        sleep 4m
        echo "Wake!"
        head /proc/cpuinfo
        head /proc/meminfo
        lsblk
        df -h .
---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: build-x86-xxlarge
  labels:
    runtimeClassName: x86-xxlarge
spec:
  params:
  steps:
    - name: build
      image: icr.io/continuous-delivery/base-images/base:v1.6.0
      script: |
        #!/bin/bash
        echo "Build x86-xxlarge!"
        sleep 8m
        echo "Wake!"
        head /proc/cpuinfo
        head /proc/meminfo
        lsblk
        df -h .
---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: build-s390x-small
  labels:
    runtimeClassName: s390x-small
spec:
  params:
  steps:
    - name: build
      image: icr.io/continuous-delivery/base-images/base:v1.6.0
      script: |
        #!/bin/bash
        echo "Build s390x-small!"
        sleep 2m
        echo "Wake!"
        head /proc/cpuinfo
        head /proc/meminfo
        lsblk
        df -h .
---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: build-s390x-medium
  labels:
    runtimeClassName: s390x-medium
spec:
  params:
  steps:
    - name: build
      image: icr.io/continuous-delivery/base-images/base:v1.6.0
      script: |
        #!/bin/bash
        echo "Build s390x-medium!"
        sleep 13m
        echo "Wake!"
        head /proc/cpuinfo
        head /proc/meminfo
        lsblk
        df -h .
---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: build-s390x-large
  labels:
    runtimeClassName: s390x-large
spec:
  params:
  steps:
    - name: build
      image: icr.io/continuous-delivery/base-images/base:v1.6.0
      script: |
        #!/bin/bash
        echo "Build s390x-large!"
        sleep 5m
        echo "Wake!"
        head /proc/cpuinfo
        head /proc/meminfo
        lsblk
        df -h .
---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: build-s390x-xlarge
  labels:
    runtimeClassName: s390x-xlarge
spec:
  params:
  steps:
    - name: build
      image: icr.io/continuous-delivery/base-images/base:v1.6.0
      script: |
        #!/bin/bash
        echo "Build s390x-xlarge!"
        sleep 4m
        echo "Wake!"
        head /proc/cpuinfo
        head /proc/meminfo
        lsblk
        df -h .
---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: build-s390x-xxlarge
  labels:
    runtimeClassName: s390x-xxlarge
spec:
  params:
  steps:
    - name: build
      image: icr.io/continuous-delivery/base-images/base:v1.6.0
      script: |
        #!/bin/bash
        echo "Build s390x-xxlarge!"
        sleep 3m
        echo "Wake!"
        head /proc/cpuinfo
        head /proc/meminfo
        lsblk
        df -h .
---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: build-ppc64-small
  labels:
    runtimeClassName: ppc64le-small
spec:
  params:
  steps:
    - name: build
      image: icr.io/continuous-delivery/base-images/base:v1.6.0
      script: |
        #!/bin/bash
        echo "Build ppc64le-small!"
        sleep 2m
        echo "Wake!"
        head /proc/cpuinfo
        head /proc/meminfo
        lsblk
        df -h .
---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: build-ppc64-medium
  labels:
    runtimeClassName: ppc64le-medium
spec:
  params:
  steps:
    - name: build
      image: icr.io/continuous-delivery/base-images/base:v1.6.0
      script: |
        #!/bin/bash
        echo "Build ppc64le-medium!"
        sleep 13m
        echo "Wake!"
        head /proc/cpuinfo
        head /proc/meminfo
        lsblk
        df -h .
---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: build-ppc64-large
  labels:
    runtimeClassName: ppc64le-large
spec:
  params:
  steps:
    - name: build
      image: icr.io/continuous-delivery/base-images/base:v1.6.0
      script: |
        #!/bin/bash
        echo "Build ppc64le-large!"
        sleep 5m
        echo "Wake!"
        head /proc/cpuinfo
        head /proc/meminfo
        lsblk
        df -h .
---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: build-ppc64-xlarge
  labels:
    runtimeClassName: ppc64le-xlarge
spec:
  params:
  steps:
    - name: build
      image: icr.io/continuous-delivery/base-images/base:v1.6.0
      script: |
        #!/bin/bash
        echo "Build ppc64le-xlarge!"
        sleep 4m
        echo "Wake!"
        head /proc/cpuinfo
        head /proc/meminfo
        lsblk
        df -h .
---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: build-ppc64-xxlarge
  labels:
    runtimeClassName: ppc64le-xxlarge
spec:
  params:
  steps:
    - name: build
      image: icr.io/continuous-delivery/base-images/base:v1.6.0
      script: |
        #!/bin/bash
        echo "Build ppc64le-xxlarge!"
        sleep 3m
        echo "Wake!"
        head /proc/cpuinfo
        head /proc/meminfo
        lsblk
        df -h .
---
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: pipeline-multiarch
spec:
  params:
  tasks:
    - name: build-small
      taskRef:
        name: build-small
    - name: build-medium
      taskRef:
        name: build-medium
    - name: build-large
      taskRef:
        name: build-large
    - name: build-x86-large
      taskRef:
        name: build-x86-large
    - name: build-x86-xlarge
      taskRef:
        name: build-x86-xlarge
    - name: build-x86-xxlarge
      taskRef:
        name: build-x86-xxlarge
    - name: build-s390x-small
      taskRef:
        name: build-s390x-small
    - name: build-s390x-medium
      taskRef:
        name: build-s390x-medium
    - name: build-s390x-large
      taskRef:
        name: build-s390x-large
    - name: build-s390x-xlarge
      taskRef:
        name: build-s390x-xlarge
    - name: build-s390x-xxlarge
      taskRef:
        name: build-s390x-xxlarge
    - name: build-ppc64-small
      taskRef:
        name: build-ppc64-small
    - name: build-ppc64-medium
      taskRef:
        name: build-ppc64-medium
    - name: build-ppc64-large
      taskRef:
        name: build-ppc64-large
    - name: build-ppc64-xlarge
      taskRef:
        name: build-ppc64-xlarge
---
apiVersion: tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: listener-multiarch
spec:
  resourcetemplates:
    - apiVersion: tekton.dev/v1
      kind: PipelineRun
      metadata:
        name: run
      spec:
        podTemplate:
          runtimeClassName: medium
        securityContext:
          privileged: true
        pipelineRef:
            name: pipeline-multiarch
---
apiVersion: tekton.dev/v1
kind: TriggerBinding
metadata:
  name: listener-multiarch
spec:
  params:
---
apiVersion: tekton.dev/v1
kind: EventListener
metadata:
  name: listener-multiarch
spec:
  triggers:
    - binding:
        name: listener-multiarch
      template:
        name: listener-multiarch
