apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: build-x86-xlarge
  labels:
     runtimeClassName: small
spec:
  params:
  workspaces:
  - name: task-pvc
    mountPath: /workspace
  steps:
    - name: build
      image: icr.io/continuous-delivery/base-images/base:v1.6.0
      script: |
        #!/bin/bash
        echo "Build x86-xlarge!"
        head /proc/cpuinfo
        head /proc/meminfo
        lsblk
        #sleep 3600
---
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: pipeline-x86-xlarge
spec:
  params:
  workspaces:
  - name: pipeline-pvc
  tasks:
    - name: build-x86-xlarge
      taskRef:
        name: build-x86-xlarge
      workspaces:
      - name: task-pvc
        workspace: pipeline-pvc
---
apiVersion: tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: listener-x86-xlarge-pvc
spec:
  resourcetemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: base-$(uid)-pvc
      spec:
        resources:
          requests:
            storage:  5Gi
        volumeMode: Filesystem
        accessModes:
          - ReadWriteOnce
    - apiVersion: tekton.dev/v1
      kind: PipelineRun
      metadata:
        name: run-$(uid)
      spec:
        podTemplate:
          runtimeClassName: x86-xlarge
        securityContext:
          privileged: true
        pipelineRef:
            name: pipeline-x86-xlarge
        workspaces:
          - name: pipeline-pvc
            persistentVolumeClaim:
              claimName: base-$(uid)-pvc
---
apiVersion: tekton.dev/v1
kind: TriggerBinding
metadata:
  name: listener-x86-xlarge-pvc
spec:
  params:
---
apiVersion: tekton.dev/v1
kind: EventListener
metadata:
  name: listener-x86-xlarge-pvc
spec:
  triggers:
    - binding:
        name: listener-x86-xlarge-pvc
      template:
        name: listener-x86-xlarge-pvc
