apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: build-x86-large
spec:
  params:
  steps:
    - name: build
      image: icr.io/continuous-delivery/base-images/base:v1.6.0
      script: |
        #!/bin/bash
        echo "Build x86-large!"
        head /proc/cpuinfo
        head /proc/meminfo
        lsblk
        #sleep 3600
---
apiVersion: tekton.dev/v1
kind: Task
metadata:
  name: build-small
  labels:
    runtimeClassName: small
spec:
  params:
  steps:
    - name: build
      image: icr.io/continuous-delivery/base-images/base:v1.6.0
      script: |
        #!/bin/bash
        echo "Build small!"
        head /proc/cpuinfo
        head /proc/meminfo
        lsblk
---
apiVersion: tekton.dev/v1
kind: Pipeline
metadata:
  name: pipeline-x86-large
spec:
  params:
  tasks:
    - name: build-x86-large
      taskRef:
        name: build-x86-large
    - name: build-small
      taskRef:
        name: build-small
---
apiVersion: tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: listener-x86-large
spec:
  resourcetemplates:
    - apiVersion: tekton.dev/v1
      kind: PipelineRun
      metadata:
        name: run-$(uid)
      spec:
        podTemplate:
          runtimeClassName: x86-large
        securityContext:
          privileged: true
        pipelineRef:
            name: pipeline-x86-large
---
apiVersion: tekton.dev/v1
kind: TriggerBinding
metadata:
  name: listener-x86-large
spec:
  params:
---
apiVersion: tekton.dev/v1
kind: EventListener
metadata:
  name: listener-x86-large
spec:
  triggers:
    - binding:
        name: listener-x86-large
      template:
        name: listener-x86-large
